version: '3'

services:
  spark-master:
    image: docker.io/bitnami/spark:3
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8082:8080'
      - '7077:7077'
    volumes:
      - './src/data:/src/data'
    networks:
      - spark
  spark-worker-1:
    image: docker.io/bitnami/spark:3
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8081:8081'
    volumes:
      - './src/data:/src/data'
    networks:
      - spark
    depends_on:
      - spark-master
  app:
    build:
      context: .
    volumes:
      - './src:/src'
    ports:
      - '5001:5001'
    networks:
      - spark
    depends_on:
      - spark-master
      - spark-worker-1
networks:
  spark:
    driver: bridge
